version: "3.8"

services:
  fastapi:
    build:
      context: app/
      dockerfile: Dockerfile
    container_name: fastapi
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:2476@db:5432/liveboard
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network
    expose:
      - "8000"

  db:
    image: postgres:17
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"  # Прокидываем порты
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network


  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - fastapi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
