"""db change

Revision ID: 499137ae91b9
Revises: 
Create Date: 2025-04-15 19:02:58.412043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '499137ae91b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'rooms', 'room_users', ['creator_id'], ['id'])
    op.add_column('site_users', sa.Column('hashed_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_users', 'hashed_password')
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    # ### end Alembic commands ###
